### ISSUE TITLE
Create a DriveSubsystem and Start Controlling Motors

### ISSUE THREAD

**Issue by FujiBookPro** [team401/Nickleback-2023#2]
Create a new subsystem for controlling the drive, and get the robot (barely) moving.

- Create a new [subsystem](https://docs.wpilib.org/en/stable/docs/software/commandbased/subsystems.html), either by deleting or renaming the `ExampleSubsystem`.
- Add dummy methods to the subsystem for controlling both sets of motors.
- [Add the Pheonixv5 vendor library](https://docs.wpilib.org/en/stable/docs/software/vscode-overview/3rd-party-libraries.html) in order to create motor controller objects.
- Create motor controller objects and implement the dummy methods to set voltage to them. Remember that there are two motors connected to each gearbox, so be careful to spin them in the same direction. You should then combine them in `MotorControllerGroup` objects, as we will need that later.
- Instantiate the subsystem in `RobotContainer`, and add button bindings to run the motors.

Does it build?  Does the robot move? Ask someone for help if you get stuck or it seems like you're breaking the robot.

Also, be sure to make a commit to [git](https://docs.wpilib.org/en/stable/docs/software/basic-programming/git-getting-started.html) often, with a message describing what you've done since your last one. We need to go over pull requests soon, but for now, just make sure you push at the end of the day. You shouldn't need to track down a specific laptop every time shop meets.

**Comment by jkleiber** [comment]
All work is done in this ticket except for RobotContainer work. This is being carried forward in #14. Closing this ticket
