### ISSUE TITLE
Start Driving With Sticks

### ISSUE THREAD

**Issue by FujiBookPro** [team401/Nickleback-2023#3]
Programming differential and mecanum drives with WPILib is very easy, as it comes with classes pre-written to do the math and logic for you. 

Start by creating a `DifferentialDrive` object and pass in the left and right motor controller groups. `DifferentialDrive` includes two methods for controlling the drive. `arcadeDrive`  takes in a forward/backward speed, and a rotation speed. `tankDrive` takes in values for the left and right speed. Pick one, write a wrapper method for it, and bind joystick axes to the inputs.

If you don't know how to do that, try adapting the code below:

```
<driveSubsystem>.setDefaultCommand(new InstantCommand(() -> {
    <driveSubsystem>.<driveMethod>(<leftStick>.getX(), <rightStick>.getY());
}));
```

We will go into detail about `InstantCommand`s and functional interfaces in time, but know for now that the code in the curly brackets runs periodically.

Now, does the code build? Does the robot drive? If so, you have successfully written some drive code! This is basically the "Hello World" of FRC.

**Comment by jkleiber** [comment]
Code has been implemented for mapping stick inputs into the drive subsystem to command the drivetrain. The remaining work to get RobotContainer correct is being done in #2. Closing this task
