### ISSUE TITLE
Arm logic

### ISSUE THREAD

**Issue by honzikschenk** [team401/Nickleback-2023#5]
Create arm logic for B Team

**Comment by jkleiber** [comment]
@minhnguyenbhs and @Bread-n-Butter06 , the block diagram for the arm is in the Controls 2023 google drive folder under Nickelback. Once it is ready we can begin to divide work and write code for the arm, ideally by the end of next meeting

**Comment by jkleiber** [comment]
A first draft of the arm code has been written. Closing this issue
