### ISSUE TITLE
B Robot Upper Motor

### ISSUE THREAD

**Issue by minhlpnguyen** [team401/Nickleback-2023#8]
![image](https://github.com/team401/Nickleback-2023/assets/93294337/1d822694-3c37-4d54-8850-7e7b4fc88d0c)

Write code for the upper motor - used when intaking cubes

**Comment by jkleiber** [comment]
Code has been written. Just FYI: it's not clear that the upper set of wheels will actually exist. if it doesn't, then this code will be removed or disabled in another issue
